version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'github_actions:pull-request'
    commit-message:
      prefix: meta
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: monthly
    labels:
      - 'github_actions:pull-request'
    commit-message:
      prefix: meta
    groups:
      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'typescript-eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'stylelint'
          - 'stylelint-*'
        exclude-patterns:
          - 'eslint-plugin-storybook'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
          - 'eslint-plugin-storybook'
      testing:
        patterns:
          - '@testing-library/*'
          - '@types/testing-library*'
          - '@types/jest'
          - 'jest'
          - 'jest-*'
      next-js:
        patterns:
          - 'next'
          - 'eslint-config-next'
          - '@next/eslint-plugin-next'
          - 'next-*'
          - '@vercel/*'
      mdx:
        patterns:
          - '@vcarl/remark-headings'
          - '@mdx-js/*'
          - 'rehype-*'
          - 'remark-*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - '@savvywombat/tailwindcss-grid-areas'
          - '@tailwindcss/container-queries'
          - 'prettier-plugin-tailwindcss'
          - 'tailwindcss'
      orama:
        patterns:
          - '@orama/*'
          - '@oramacloud/*'
    ignore:
      # Manually update major versions of @types/node with the version specified within .nvmrc
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10
