blank_issues_enabled: false
contact_links:
  - name: â‰ï¸ Need help with Node.js?
    url: https://github.com/nodejs/help/issues/
    about: File an issue in our help repo.
  - name: ğŸ“— Node.js API Docs
    url: https://github.com/nodejs/node/issues/new?assignees=&labels=doc&template=3-api-ref-docs-problem.yml
    about: Please open an issue in the main Node.js repo.
