name: Build and Analysis Checks

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read
  actions: read
  pull-requests: write

env:
  TURBO_REF_FILTER: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Use GNU tar instead BSD tar
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - name: Git Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - name: Restore Cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ~/.npm
            .next/cache
            node_modules/.cache
          restore-keys: |
            cache-${{ hashFiles('package-lock.json') }}-
            cache-

      - name: Set up Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install NPM packages
        run: npm ci --no-audit --no-fund --omit=dev

      - name: Build Next.js
        run: npx turbo build
        env:
          TURBO_FORCE: true
          NODE_OPTIONS: '--max_old_space_size=4096'
          NEXT_TELEMETRY_DISABLED: 1

      - name: Analyse Build
        run: npx -p nextjs-bundle-analysis report

      - name: Upload Build Analysis
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: bundle-analysis
          path: .next/analyze/__bundle_analysis.json

      - name: Save Cache
        uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ~/.npm
            .next/cache
            node_modules/.cache
          key: cache-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.next/cache/**') }}

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Git Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Restore Cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ~/.npm
            .next/cache
            node_modules/.cache
          restore-keys: |
            cache-${{ hashFiles('package-lock.json') }}-
            cache-

      - name: Download PR Bundle Analysis
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: bundle-analysis
          path: .next/analyze

      - name: Download Base Bundle Analysis
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        if: success() && github.event.number
        with:
          name: bundle-analysis
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base/bundle
          if_no_artifact_found: warn

      - name: Check Base Bundle Analysis File
        id: check-base-bundle-analysis-file
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b
        with:
          files: .next/analyze/base/bundle/__bundle_analysis.json

      - name: Copy PR Bundle Analysis (Fallback)
        if: steps.check-base-bundle-analysis-file.outputs.files_exists == 'true'
        run: |
          mkdir -p .next/analyze/base/bundle/
          cp .next/analyze/__bundle_analysis.json .next/analyze/base/bundle/__bundle_analysis.json

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Get Comment Body
        id: get-comment-body
        if: success() && github.event.number
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1
        if: success() && github.event.number
        id: find-comment-id
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE_nodejs.org -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@c6c9a1a66007646a28c153e2a8580a5bad27bcfa
        if: success() && github.event.number && steps.find-comment-id.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@c6c9a1a66007646a28c153e2a8580a5bad27bcfa
        if: success() && github.event.number && steps.find-comment-id.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.find-comment-id.outputs.comment-id }}
          edit-mode: replace
